#!/usr/bin/env python3
"""Setup script to download and configure Grounded-SAM2 models."""

import os
import sys
from pathlib import Path
import urllib.request
import argparse
from tqdm import tqdm

class DownloadProgressBar(tqdm):
    def update_to(self, b=1, bsize=1, tsize=None):
        if tsize is not None:
            self.total = tsize
        self.update(b * bsize - self.n)

def download_file(url, output_path):
    """Download file with progress bar."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    if output_path.exists():
        print(f"  File already exists: {output_path}")
        return
    
    print(f"  Downloading to: {output_path}")
    with DownloadProgressBar(unit='B', unit_scale=True, miniters=1, desc=output_path.name) as t:
        urllib.request.urlretrieve(url, filename=str(output_path), reporthook=t.update_to)

def setup_models(base_dir="~/models"):
    """Download and setup Grounded-SAM2 models."""
    base_dir = Path(base_dir).expanduser()
    base_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"Setting up models in: {base_dir}")
    
    # SAM2 models
    sam2_dir = base_dir / "segment-anything-2"
    sam2_ckpt_dir = sam2_dir / "checkpoints"
    sam2_ckpt_dir.mkdir(parents=True, exist_ok=True)
    
    sam2_models = {
        "sam2_hiera_tiny.pt": "https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_tiny.pt",
        "sam2_hiera_small.pt": "https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_small.pt",
        "sam2_hiera_base_plus.pt": "https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_base_plus.pt",
        "sam2_hiera_large.pt": "https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_large.pt",
    }
    
    print("\n1. Downloading SAM2 models...")
    for filename, url in sam2_models.items():
        if "base_plus" in filename:  # Prioritize the recommended model
            download_file(url, sam2_ckpt_dir / filename)
    
    # Grounding DINO models
    grounding_dir = base_dir / "GroundingDINO"
    grounding_weights_dir = grounding_dir / "weights"
    grounding_weights_dir.mkdir(parents=True, exist_ok=True)
    
    grounding_models = {
        "groundingdino_swint_ogc.pth": "https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth",
        "groundingdino_swinb_cogcoor.pth": "https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha2/groundingdino_swinb_cogcoor.pth",
    }
    
    print("\n2. Downloading Grounding DINO models...")
    for filename, url in grounding_models.items():
        if "swinb" in filename:  # Prioritize the recommended model
            download_file(url, grounding_weights_dir / filename)
    
    # Create config files
    print("\n3. Creating config files...")
    
    # SAM2 configs
    sam2_config_dir = sam2_dir / "sam2_configs"
    sam2_config_dir.mkdir(parents=True, exist_ok=True)
    
    # Basic config template (simplified)
    config_template = """# SAM2 Model Configuration
model:
  _target_: sam2.modeling.sam2_base.SAM2Base
  image_encoder:
    _target_: sam2.modeling.backbones.image_encoder.ImageEncoder
    scalp: 1
    trunk:
      _target_: sam2.modeling.backbones.hieradet.Hiera
      stages: [2, 3, 16, 3]
      global_att_blocks: [12, 16, 20]
      window_pos_embed_bkg_spatial_size: [14, 14]
  memory_attention:
    _target_: sam2.modeling.memory_attention.MemoryAttention
    d_model: 256
  memory_encoder:
    _target_: sam2.modeling.memory_encoder.MemoryEncoder
"""
    
    config_path = sam2_config_dir / "hiera_b+.yaml"
    if not config_path.exists():
        config_path.write_text(config_template)
        print(f"  Created: {config_path}")
    
    # Create model path configuration
    model_config = f"""# Grounded-SAM2 Model Paths Configuration
# Auto-generated by setup_grounded_sam2_models.py

SAM2_CHECKPOINT_DIR = "{sam2_ckpt_dir}"
GROUNDING_DINO_CHECKPOINT_DIR = "{grounding_weights_dir}"

# Model paths
SAM2_MODELS = {{
    "hiera_tiny": "{sam2_ckpt_dir}/sam2_hiera_tiny.pt",
    "hiera_small": "{sam2_ckpt_dir}/sam2_hiera_small.pt",
    "hiera_b+": "{sam2_ckpt_dir}/sam2_hiera_base_plus.pt",
    "hiera_large": "{sam2_ckpt_dir}/sam2_hiera_large.pt",
}}

GROUNDING_DINO_MODELS = {{
    "grounding_dino_swin-t": "{grounding_weights_dir}/groundingdino_swint_ogc.pth",
    "grounding_dino_swin-b": "{grounding_weights_dir}/groundingdino_swinb_cogcoor.pth",
}}
"""
    
    config_file = base_dir / "grounded_sam2_paths.py"
    config_file.write_text(model_config)
    print(f"\n4. Created model path configuration: {config_file}")
    
    print("\n✅ Setup complete!")
    print(f"\nModels installed in: {base_dir}")
    print("\nTo use these models:")
    print("1. Set use_mock: false in config/semantic_slam.yaml")
    print("2. Run: python main_semantic.py --config config/semantic_slam.yaml --dataset <path>")
    
    return base_dir

def main():
    parser = argparse.ArgumentParser(description="Setup Grounded-SAM2 models")
    parser.add_argument("--model-dir", default="~/models", 
                       help="Directory to store models (default: ~/models)")
    parser.add_argument("--download-all", action="store_true",
                       help="Download all model variants (default: only recommended)")
    args = parser.parse_args()
    
    setup_models(args.model_dir)

if __name__ == "__main__":
    main()