#!/usr/bin/env python3
"""
Semantic PLY Viewer for MASt3R-SLAM
Visualize and query semantic point clouds generated by MASt3R-SLAM
"""

import argparse
import json
import numpy as np
try:
    import open3d as o3d
except ImportError:
    print("Error: Open3D is not installed. Please install it with:")
    print("  pip install open3d")
    exit(1)
from pathlib import Path
from plyfile import PlyData
import colorsys


class SemanticPLYViewer:
    def __init__(self, ply_path, semantic_map_path=None):
        """
        Initialize the semantic PLY viewer.
        
        Args:
            ply_path: Path to the PLY file
            semantic_map_path: Path to the semantic map JSON (optional)
        """
        self.ply_path = Path(ply_path)
        self.semantic_map_path = semantic_map_path
        
        # Load PLY data
        self.ply_data = PlyData.read(ply_path)
        self.vertices = self.ply_data['vertex']
        
        # Extract point cloud data
        self.points = np.vstack([
            self.vertices['x'],
            self.vertices['y'],
            self.vertices['z']
        ]).T
        
        self.rgb_colors = np.vstack([
            self.vertices['red'],
            self.vertices['green'],
            self.vertices['blue']
        ]).T / 255.0
        
        # Extract semantic labels
        self.semantic_ids = None
        vertex_dtype = self.vertices.data.dtype
        for prop in ['semantic_id', 'quality']:
            if prop in vertex_dtype.names:
                self.semantic_ids = self.vertices.data[prop]
                print(f"Found semantic labels in property '{prop}'")
                break
        
        if self.semantic_ids is None:
            print("Warning: No semantic labels found in PLY file")
            self.semantic_ids = np.zeros(len(self.points), dtype=np.int32)
        
        # Load semantic map
        self.semantic_map = self._load_semantic_map()
        
        # Generate semantic colors
        self.semantic_colors = self._generate_semantic_colors()
        
        # Create Open3D point cloud
        self.pcd = o3d.geometry.PointCloud()
        self.pcd.points = o3d.utility.Vector3dVector(self.points)
        self.pcd.colors = o3d.utility.Vector3dVector(self.rgb_colors)
        
        # Current display mode
        self.show_semantic = False
        self.filtered_classes = set()
        
    def _load_semantic_map(self):
        """Load semantic map from JSON file or PLY comments."""
        semantic_map = {0: "background"}
        
        # Try loading from JSON file
        if self.semantic_map_path and Path(self.semantic_map_path).exists():
            with open(self.semantic_map_path, 'r') as f:
                json_map = json.load(f)
                # Convert string keys to integers
                semantic_map = {int(k): v for k, v in json_map.items()}
                print(f"Loaded semantic map from {self.semantic_map_path}")
        else:
            # Try extracting from PLY comments
            if hasattr(self.ply_data, 'comments'):
                in_label_map = False
                for comment in self.ply_data.comments:
                    if comment == 'label_map_start':
                        in_label_map = True
                    elif comment == 'label_map_end':
                        in_label_map = False
                    elif in_label_map and comment.startswith('label_id'):
                        # Parse "label_id {id}: {name}"
                        parts = comment.split(':', 1)
                        if len(parts) == 2:
                            label_id = int(parts[0].split()[-1])
                            label_name = parts[1].strip()
                            semantic_map[label_id] = label_name
                
                if len(semantic_map) > 1:
                    print("Loaded semantic map from PLY comments")
        
        return semantic_map
    
    def _generate_semantic_colors(self):
        """Generate distinct colors for each semantic class."""
        unique_ids = np.unique(self.semantic_ids)
        colors = np.zeros((len(self.points), 3))
        
        # Generate distinct colors using HSV
        for i, label_id in enumerate(unique_ids):
            if label_id == 0:
                # Background is dark gray
                color = [0.2, 0.2, 0.2]
            else:
                # Generate distinct color
                hue = (i - 1) * 360.0 / (len(unique_ids) - 1)
                color = colorsys.hsv_to_rgb(hue/360.0, 0.8, 0.9)
            
            mask = self.semantic_ids == label_id
            colors[mask] = color
        
        return colors
    
    def get_object_stats(self):
        """Get statistics about objects in the scene."""
        unique_ids, counts = np.unique(self.semantic_ids, return_counts=True)
        
        print("\n=== Object Statistics ===")
        print(f"Total points: {len(self.points):,}")
        print(f"Unique objects: {len(unique_ids)}")
        print("\nObject counts:")
        
        for label_id, count in zip(unique_ids, counts):
            label_name = self.semantic_map.get(label_id, f"unknown_{label_id}")
            percentage = count / len(self.points) * 100
            print(f"  {label_id:3d}: {label_name:20s} - {count:8,} points ({percentage:5.1f}%)")
    
    def filter_by_class(self, class_names):
        """Filter point cloud to show only specific classes."""
        if isinstance(class_names, str):
            class_names = [class_names]
        
        # Find label IDs for the requested classes
        label_ids = []
        for name in class_names:
            for label_id, label_name in self.semantic_map.items():
                if name.lower() in label_name.lower():
                    label_ids.append(label_id)
        
        if not label_ids:
            print(f"No objects found matching: {class_names}")
            return None
        
        # Create filtered point cloud
        mask = np.isin(self.semantic_ids, label_ids)
        filtered_points = self.points[mask]
        filtered_colors = self.semantic_colors[mask] if self.show_semantic else self.rgb_colors[mask]
        
        filtered_pcd = o3d.geometry.PointCloud()
        filtered_pcd.points = o3d.utility.Vector3dVector(filtered_points)
        filtered_pcd.colors = o3d.utility.Vector3dVector(filtered_colors)
        
        print(f"Filtered to {len(filtered_points):,} points from classes: {class_names}")
        return filtered_pcd
    
    def export_filtered(self, output_path, class_names):
        """Export filtered point cloud to PLY file."""
        filtered_pcd = self.filter_by_class(class_names)
        if filtered_pcd:
            o3d.io.write_point_cloud(output_path, filtered_pcd)
            print(f"Exported filtered point cloud to {output_path}")
    
    def toggle_semantic_colors(self):
        """Toggle between RGB and semantic colors."""
        self.show_semantic = not self.show_semantic
        if self.show_semantic:
            self.pcd.colors = o3d.utility.Vector3dVector(self.semantic_colors)
            print("Showing semantic colors")
        else:
            self.pcd.colors = o3d.utility.Vector3dVector(self.rgb_colors)
            print("Showing RGB colors")
    
    def visualize(self, window_name="MASt3R-SLAM Semantic Viewer"):
        """Launch interactive visualization."""
        print("\n=== Controls ===")
        print("Mouse:")
        print("  Left button + drag: Rotate")
        print("  Scroll: Zoom")
        print("  Middle button + drag: Pan")
        print("\nKeyboard:")
        print("  S: Toggle semantic/RGB colors")
        print("  R: Reset camera view")
        print("  Q: Quit")
        print("  +/-: Increase/decrease point size")
        print("\n" + "="*40)
        
        # Create visualizer
        vis = o3d.visualization.VisualizerWithKeyCallback()
        vis.create_window(window_name, width=1280, height=720)
        
        # Add point cloud
        vis.add_geometry(self.pcd)
        
        # Key callbacks
        def toggle_colors(vis):
            self.toggle_semantic_colors()
            vis.update_geometry(self.pcd)
            return False
        
        vis.register_key_callback(ord("S"), toggle_colors)
        
        # Set render options
        vis.get_render_option().point_size = 2.0
        vis.get_render_option().background_color = np.array([0.1, 0.1, 0.1])
        
        # Run visualizer
        vis.run()
        vis.destroy_window()


def main():
    parser = argparse.ArgumentParser(description="Visualize semantic PLY files from MASt3R-SLAM")
    parser.add_argument("ply_file", help="Path to PLY file")
    parser.add_argument("--semantic-map", help="Path to semantic map JSON file")
    parser.add_argument("--stats", action="store_true", help="Show object statistics")
    parser.add_argument("--filter", nargs="+", help="Filter by object class names")
    parser.add_argument("--export", help="Export filtered point cloud to file")
    parser.add_argument("--semantic", action="store_true", help="Start with semantic colors")
    
    args = parser.parse_args()
    
    # Create viewer
    viewer = SemanticPLYViewer(args.ply_file, args.semantic_map)
    
    # Show statistics if requested
    if args.stats:
        viewer.get_object_stats()
    
    # Set initial color mode
    if args.semantic:
        viewer.toggle_semantic_colors()
    
    # Handle filtering and export
    if args.filter:
        if args.export:
            viewer.export_filtered(args.export, args.filter)
        else:
            filtered_pcd = viewer.filter_by_class(args.filter)
            if filtered_pcd:
                # Visualize filtered result
                viewer.pcd = filtered_pcd
    
    # Launch visualization
    viewer.visualize()


if __name__ == "__main__":
    main()