# Grounded-SAM2 Model Paths Configuration
# Auto-generated by setup_grounded_sam2_models.py

SAM2_CHECKPOINT_DIR = "/home/ubuntu/models/segment-anything-2/checkpoints"
GROUNDING_DINO_CHECKPOINT_DIR = "/home/ubuntu/models/GroundingDINO/weights"

# Model paths
SAM2_MODELS = {
    "hiera_tiny": "/home/ubuntu/models/segment-anything-2/checkpoints/sam2_hiera_tiny.pt",
    "hiera_small": "/home/ubuntu/models/segment-anything-2/checkpoints/sam2_hiera_small.pt",
    "hiera_b+": "/home/ubuntu/models/segment-anything-2/checkpoints/sam2_hiera_base_plus.pt",
    "hiera_large": "/home/ubuntu/models/segment-anything-2/checkpoints/sam2_hiera_large.pt",
}

GROUNDING_DINO_MODELS = {
    "grounding_dino_swin-t": "/home/ubuntu/models/GroundingDINO/weights/groundingdino_swint_ogc.pth",
    "grounding_dino_swin-b": "/home/ubuntu/models/GroundingDINO/weights/groundingdino_swinb_cogcoor.pth",
}
